name: Printing new things
on: [push]
defaults:
  run:
    shell: bash

jobs:
  Run-commands:
    runs-on: ubuntu-latest
    steps:
      - name: Print the linux commands
        run: |
          pwd
          ls -a

  Print-keys:
    runs-on: ubuntu-latest
    steps:
       - name: Print keys
         run: |
           echo "$GITHUB_SHA"
           cat "$.gitignore"
  
