name: Simple Manual Workflow

on:
  workflow_dispatch:

jobs:
  hello_job:
    runs-on: ubuntu-latest
    steps:
      - name: Print a message
        run: echo "Hello from workflow_dispatch!"

      
    
